ratings:
  paths:
  - app/controllers/**
  # - "**.rb"
exclude_paths:
- spec/**
- bin/**
- config/**
- features/**
- iterations/**
- lib/**
- log/**
- public/**
- script/**
- spec/**
- tmp/**
- vendor/**
- fullcalendar-rails-engine/**