language: ruby
rvm:
  - 2.2.5
env:
  - DB=pgsql
bundler_args: --without production
before-script:
  - psql -c 'create database my_database_test;' -U postgres
script:
  - rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
after_script:
  - bundle exec rake send_to_codeclimate
services:
  - postgresql
